import type Account from "@common/models/account";
import type Room from "@common/models/room";
import type BattleState from "@common/models/battleState";
import type ActionResolved from "@common/models/actionResolved";
import type SceneState from "@common/models/sceneState";
import type { TreasuresApplying } from "@common/models/treasuresApplying";
import type { Modal } from "./modal";
import MessageClient from "@common/communicator/message_client";

export default interface OutletContext {
  account: Account | null;
  setOutgoingToAdd: (nextOutgoingToAdd: MessageClient | null) => void;
  room: Room | null;
  battleState: BattleState | null;
  setBattleState: (nextBattleState: BattleState | null) => void;
  battleStateLast: BattleState | null;
  setBattleStateLast: (nextBattleState: BattleState | null) => void;
  battleStateFuture: BattleState | null;
  setBattleStateFuture: (nextBattleState: BattleState | null) => void;
  actionsResolved: ActionResolved[] | null;
  setActionsResolved: (nextActionsResolved: ActionResolved[] | null) => void;
  actionsResolvedFuture: ActionResolved[] | null;
  setActionsResolvedFuture: (nextActionsResolved: ActionResolved[] | null) => void;
  toCommand: string | null;
  sceneState: SceneState | null;
  setSceneState: (nextScene: SceneState | null) => void;
  treasuresApplying: TreasuresApplying | null;
  setTreasuresApplying: (nextTreasuresApplying: TreasuresApplying | null) => void;
  setModalToAdd: (modal: Modal) => void;
};